### ISSUE TITLE
Representers for collections

### ISSUE THREAD

**Issue by rusikf** [apotonick/representable#149]
Let's we have
```ruby
require 'pry'
require 'ostruct'
require 'representable/json'

class Song < OpenStruct
end

module SongRepresenter
  include Representable::Hash
  property :title
  collection_representer class: Song
end

song1 = Song.new(title: "Sevens")
song2 = Song.new(title: "Eric")
puts SongRepresenter.represent([song1,song2]).to_hash
#{"title"=>"Sevens"}
#{"title"=>"Eric"}

puts [].extend(SongRepresenter.for_collection).from_hash([{"title" => "Sevens"}, {"title" =>"Eric"}]).to_hash
#{"title"=>"Sevens"}
#{"title"=>"Eric"}
```
Why we don't have array wrapper on result ? ([docs](http://www.rubydoc.info/gems/representable/#Representing_Singular_Models_And_Collections))

**Comment by apotonick** [comment]
Not sure what you mean?! :grimacing: The `to_hash` method wraps a collection in an array: https://github.com/apotonick/representable/blob/master/test/represent_test.rb#L9

In your second example, you're doing it wrong, you have to do 
```ruby
arr = [].extend(SongRepresenter.for_collection).from_hash([{"title" => "Sevens"}, {"title" =>"Eric"}])

SongRepresenter.represent(arr).to_hash
```

Otherwise representable doesn't know whether or not to represent a single object or an array.
