### ISSUE TITLE
How to use document nesting?

### ISSUE THREAD

**Issue by rusikf** [apotonick/representable#150]
Let's we have
```ruby
require 'pry'
require 'ostruct'
require 'representable/json'

hash = { 
 "title" => "Roxanne",
 "details" => { "track" => 3, "length" => "4:10"}
}

class Song < OpenStruct
end

class SongRepresenter < Representable::Decorator
  include Representable::JSON

  property :title

  nested :details do
    property :track
    property :length
  end
end

puts SongRepresenter.represent(Song.new).from_hash(hash)
# #<Song title="Roxanne", track=3, length="4:10">
```
Why I don't see nested results( ```details``` wrapper) on results?( [doc](http://www.rubydoc.info/gems/representable/#Document_Nesting))

**Comment by apotonick** [comment]
Because `details` is only a document element and not a property on your object, that's the whole point of `::nested`. It helps you when the document has nesting but the actual represented object doesn't. Remember - a representer (without nested properties) is an instruction on how to render parse a "flat" object.

**Comment by rusikf** [comment]
Ok, thank's for explanation !
